// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iKm2w5zQkVZvuqT51PP4Eo
// Component: cIG6OIuy1Z

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_idea_stats_v_1.module.css"; // plasmic-import: iKm2w5zQkVZvuqT51PP4Eo/projectcss
import sty from "./PlasmicSelectTemplate.module.css"; // plasmic-import: cIG6OIuy1Z/css

export type PlasmicSelectTemplate__VariantMembers = {};
export type PlasmicSelectTemplate__VariantsArgs = {};
type VariantPropType = keyof PlasmicSelectTemplate__VariantsArgs;
export const PlasmicSelectTemplate__VariantProps = new Array<VariantPropType>();

export type PlasmicSelectTemplate__ArgsType = {};
type ArgPropType = keyof PlasmicSelectTemplate__ArgsType;
export const PlasmicSelectTemplate__ArgProps = new Array<ArgPropType>();

export type PlasmicSelectTemplate__OverridesType = {
  root?: p.Flex<"button">;
};

export interface DefaultSelectTemplateProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSelectTemplate__RenderFunc(props: {
  variants: PlasmicSelectTemplate__VariantsArgs;
  args: PlasmicSelectTemplate__ArgsType;
  overrides: PlasmicSelectTemplate__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
      onClick={async event => {
        const $steps = {};
        $steps["goToAdPrompt"] = true
          ? (() => {
              const actionArgs = {
                destination: __wrapUserFunction(
                  {
                    type: "InteractionArgLoc",
                    actionName: "navigation",
                    interactionUuid: "n187EVVl4",
                    componentUuid: "cIG6OIuy1Z",
                    argName: "destination"
                  },
                  () => `/ad-prompt`
                )
              };
              return __wrapUserFunction(
                {
                  type: "InteractionLoc",
                  actionName: "navigation",
                  interactionUuid: "n187EVVl4",
                  componentUuid: "cIG6OIuy1Z"
                },
                () =>
                  (({ destination }) => {
                    location.assign(destination);
                  })?.apply(null, [actionArgs]),
                actionArgs
              );
            })()
          : undefined;
        if (
          typeof $steps["goToAdPrompt"] === "object" &&
          typeof $steps["goToAdPrompt"].then === "function"
        ) {
          $steps["goToAdPrompt"] = await __wrapUserPromise(
            {
              type: "InteractionLoc",
              actionName: "navigation",
              interactionUuid: "n187EVVl4",
              componentUuid: "cIG6OIuy1Z"
            },
            $steps["goToAdPrompt"]
          );
        }
      }}
    >
      {"Select"}
    </button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSelectTemplate__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSelectTemplate__VariantsArgs;
    args?: PlasmicSelectTemplate__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSelectTemplate__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSelectTemplate__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSelectTemplate__ArgProps,
          internalVariantPropNames: PlasmicSelectTemplate__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSelectTemplate__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSelectTemplate";
  } else {
    func.displayName = `PlasmicSelectTemplate.${nodeName}`;
  }
  return func;
}

export const PlasmicSelectTemplate = Object.assign(
  // Top-level PlasmicSelectTemplate renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSelectTemplate
    internalVariantProps: PlasmicSelectTemplate__VariantProps,
    internalArgProps: PlasmicSelectTemplate__ArgProps
  }
);

export default PlasmicSelectTemplate;
/* prettier-ignore-end */
