// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAdPromptSelected,
  DefaultAdPromptSelectedProps
} from "./plasmic/idea_stats_v_1/PlasmicAdPromptSelected";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useLocation, useNavigate } from "react-router-dom";
import TextInput from "./TextInput";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface AdPromptSelectedProps extends Omit<DefaultAdPromptSelectedProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultAdPromptSelectedProps altogether and have
// total control over the props for your component.
export interface AdPromptSelectedProps extends DefaultAdPromptSelectedProps {}

function AdPromptSelected_(
  props: AdPromptSelectedProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicAdPromptSelected to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicAdPromptSelected are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all AdPromptSelectedProps here, but feel free
  // to do whatever works for you.

  let navigate = useNavigate();
  let location = useLocation();

  let imgSrc = process.env.REACT_APP_DEFAULT_AD_IMG;
  if ("adImgSrc" in location.state){
    imgSrc =  location.state.adImgSrc;
  }

  let [titleString, setTitleString] = React.useState("Hello");
  let [bodyString, setBodyString] = React.useState("Ad body. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
  let [callToActionString, setCallToActionString] = React.useState("Sign Up");
  

  return <PlasmicAdPromptSelected 
  
    root={{ ref }}

    adTemplate1={{
      adImgSrc: imgSrc,

      // Customization in template.
      title: <h2 className="plasmic_idea_stats_v_1_all__vC+pC plasmic_idea_stats_v_1_h2__TiAPZ PlasmicAdPromptSelected_h2__xlLfB">{titleString}</h2>,
      body: <div className="plasmic_idea_stats_v_1_all__vC+pC PlasmicAdPromptSelected_text__edznr__A+5F-">{bodyString}</div>,
      callToAction: {
        children: callToActionString
      }
    }}
    
    selectButton={{
      onClick: () => {
        navigate("/finished-ad");
      }
    }}

    form1={{
      children: <TextInput onChange={ (event) => { setTitleString(event.target.value) } } ></TextInput>
    }}
    
    {...props} />;
}

const AdPromptSelected = React.forwardRef(AdPromptSelected_);
export default AdPromptSelected;
